defensive_powers_list = {"Body Armor": [1], "Force Field": [1], "Force Field vs Emotion": [1],
                            "Force Field vs Energy": [1], "Force Field vs Magic": [1],
                            "Force Field vs Mental": [1], "Force Field vs Physical": [1],
                            "Force Field vs Power Manipulation": [1], "Force Field vs Vampirism": [1],
                            "Reflection": [1], "Resist: Emotion": [1], "Resist: Energy": [1],
                            "Resist: Magic": [1], "Resist: Mental": [1], "Resist: Physical": [1],
                            "Resist: Power Manipulation": [1], "Resist: Vampirism": [1]}
        
detection_powers_list = {"Abnormal Sensitivity": [1], "Circular Vision": [1],
                            "Energy Detection": [1], "Environmental Awareness": [1],
                            "Extradimensional Detection": [1], "Hyper-Hearing": [1], "Hyper-Olfactory": [1],
                            "Hyper-Touch": [1], "Life Detection": [1], "Magic Detection": [1],
                            "Microscopic Vision": [1], "Penetration Vision": [1], "Power Detection": [1],
                            "Psionic Detection": [1], "Radarsense": [1], "Sonar": [1],
                            "Telescopic Vision": [1], "Thermal Vision": [1], "Tracking": [1],
                            "True Sight": [1], "UV Vision": [1], "Weakness Detection": [1]}
        
energy_control_powers_list = {"Absorption Power": [1], "Catalytic Control": [1],
                            "Coldshaping": [1, {"bonus": ["Cold Generation"], 
                                                "option": ["Thermal Control", 
                                                           "Condensation", "Molding", 
                                                           "Body Coating"]}], 
                            "Darkforce Manipulation": [1], "Electrical Control": [1, {"bonus": [], 
                                                "option": ["Electrical Generation", 
                                                           "Energy Doppelganger", "Energy Sheath", 
                                                           "Energy Body*", "Carrier Wave", "Energy Path"]}],
                            "Energy Conversion": [1], "Energy Solidification": [1, {"bonus": [], 
                                                "option": ["Energy Emission", "Energy Control"]}], 
                            "Energy Sponge": [1], "Energy Vampirism": [1], 
                            "Fire Control": [1, {"bonus": [], 
                                                "option": ["Fire Generation", "Thermal Control", 
                                                           "Energy Sheath", "Energy Body*"]}],
                            "Gravity Manipulation": [1], "Hard Radiation Control": [1, {"bonus": [], 
                                                "option": ["Hard Radiation Emission", "Energy Doppelganger", 
                                                           "Energy Sheath", "Energy Body*", "Energy Sustenance"]}],
                            "Kinetic Control": [1, {"bonus": ["Telekinesis", "Kinetic Bolt"], 
                                                "option": ["Telekinesis", "Kinetic Bolt"]}], 
                            "Light Control": [1, {"bonus": [], 
                                                "option": ["Light Generation", "Energy Sheath", 
                                                           "Carrier Wave", "Illusion-Casting*"]}], 
                            "Magnetic Manipulation": [1],
                            "Plasma Control": [1, {"bonus": [], 
                                                "option": ["Plasma Generation", "Energy Doppelganger", 
                                                           "Energy Sheath", "Energy Body*"]}], 
                            "Radiowave Control": [1, {"bonus": ["Radiowave Generation"], 
                                                "option": ["Energy Doppelganger", "Energy Sheath", "Carrier Wave"]}],
                            "Shadowshaping": [1, {"bonus": ["Shadowcasting"], 
                                                "option": ["Light Control", "Energy Sheath", "Energy Body*"]}], 
                            "Sound Manipulation": [1, {"bonus": ["Sonic Generation"], 
                                                "option": ["Vibration Generation", "Vibration Control"]}],
                            "Thermal Control": [1, {"bonus": [], 
                                                "option": ["Heat Generation", "Fire Generation", 
                                                           "Cold Generation", "Fire Control", "Coldshaping"]}], 
                            "Vibration Control": [1, {"bonus": [], 
                                                "option": ["Vibration Generation", "Sonic Generation", 
                                                           "Sound Manipulation"]}]}
        
energy_emission_powers_list = {"Cold Generation": [1, {"bonus": [], 
                                                "option": ["Coldshaping", "Condensation", 
                                                           "Energy Solidification", "Molding"]}], 
                            "Electrical Generation": [1],
                            "Energy Doppelganger": [1], "Fire Generation": [1], "Hard Radiation Emission": [1],
                            "Heat Generation": [1], "Kinetic Bolt": [1, {"bonus": [], 
                                                "option": ["Kinetic Control", "Telekinesis"]}], 
                            "Light Emission": [1],
                            "Magnetic Generation": [1], "Plasma Generation": [1], 
                            "Radiowave Generation": [1, {"bonus": [], 
                                                "option": ["Radiowave Control", "Energy Sheath", "Carrier Wave"]}],
                            "Shadowcasting": [1, {"bonus": [], 
                                                "option": ["Shadowshaping", "Darkforce Manipulation"]}],
                            "Sonic Generation": [1, {"bonus": [], 
                                                "option": ["Sound Manipulation", "Vibration",
                                                           "Vibration Control"]}], 
                            "Vibration Generation": [1, {"bonus": [], 
                                                "option": ["Sonic Generation", "Vibration Control"]}]}
        
fighting_powers_list = {"Berserker": [1, {"bonus": [], 
                                                "option": ["Natural Weaponry"]}], 
                            "Martial Arts Supremacy": [1, {"bonus": [], 
                                                "option": ["Iron Will", "Weapons Creation*"]}],
                            "Natural Weaponry": [1], "Weapons Creation*": [2, {"bonus": [], 
                                                "option": ["Martial Arts Supremacy"]}], 
                            "Weapons Tinkering": [1], "Unique Weapon": [1]}
        
illusory_powers_list = {"Animate Image": [1, {"bonus": [], 
                                                "option": ["Telescopic Vision", "Clairvoyance", ""
                                                "Energy Solidification", "Elemental Creation", 
                                                "Molecular Creation"]}], 
                            "Illusion-Casting*": [2, {"bonus": [], 
                                                "option": ["Energy Solidification", "Telescopic Vision",
                                                           "Clairvoyance"]}],
                            "Illusory Invisibility": [1, {"bonus": [], 
                                                "option": ["Light Control", "Light Emission"]}], 
                            "Illusory Duplication": [1]}
        
lifeform_control_powers_list = {"Biophysical Control*": [2, {"bonus": [], 
                                                "option": ["Biophysical Control*"]}], 
                            "Bio-Vampirism*": [2], "Body Transformation-Others": [1], "Emotion Control": [1],
                            "Exorcism": [1], "Force Field vs Hostiles": [1], "Forced Reincarnation": [1],
                            "Grafting*": [2], "Hypnotic Control": [1], "Mind Control*": [2],
                            "Mind Transferral*": [2], "Neural Manipulation": [1], "Plague Carrier": [1],
                            "Plant Control": [1], "Plant Growth": [1], "Sense Alteration": [1],
                            "Shapechange-Others*": [2], "Sleep-Induced": [1], "Spirit Storage": [1],
                            "Summoning": [1], "Undead Control": [1]}

magic_powers_list = {"Enchantment*": [2, {"bonus": [], 
                                                "option": ["Elemental Conversion*", "Molecular Conversion*",
                                                           "Molding"]}], 
                            "Energy Source": [1], "Internal Limbo": [1, {"bonus": [], 
                                                "option": ["Energy Doppelganger", 
                                                           "Illusory Duplication", "Lifeform Creation*", 
                                                           "Free Spirit*", "Anatomical Separation", 
                                                           "Self-Duplication*", "Astral Body"]}],
                            "Magic Control*": [2], "Magic Creation*": [2, {"bonus": [], 
                                                "option": ["Hyper-Intelligence", "Total Memory"]}], 
                            "Magic Domination": [1, {"bonus": [], 
                                                "option": ["Mind Control*", "Power Domination*"]}],
                            "Magic Transferral": [1, {"bonus": [], 
                                                "option": ["Mind Transferral*", "Power Transferral"]}], 
                            "Magic Vampirism": [1], "Power Simulation": [1],
                            "Reality Alteration*": [2, {"bonus": [], 
                                                "option": ["Precognition*", "Clairvoyance", "Postcognition"]}], 
                            "Spirit Vampirism*": [2, {"bonus": [], 
                                                "option": ["Bio-Vampirism*"]}], 
                            "Sympathetic Magic": [1], "Warding*": [1], "Probability Control": [1]}

matter_control_powers_list = {"Bonding": [1, {"bonus": [], 
                                                "option": ["Missile Creation", "Spray", 
                                                           "Webcasting", "Weapons Tinkering"]}], 
                            "Collection": [1, {"bonus": [], 
                                                "option": ["Matter Control", "Crystallization", 
                                                "Matter Animation*", "Micro Environment", "Molding", 
                                                "Weather Control", "Combustion", "Elemental Conversion*",
                                                "Molecular Conversion*"]}], 
                            "Crystallization": [1, {"bonus": [], 
                                                "option": ["Weapons Creation*", "Collection", 
                                                           "Matter Animation*", "Missile Creation", "Spray"]}],
                            "Diminution": [1], "Disruption": [1], "Enlargement": [1], "Geoforce": [1],
                            "Matter Animation*": [2], "Machine Animation*": [2, {"bonus": [], 
                                                "option": ["Matter Control", "Communication with Cybernetics", 
                                                           "Communication with Non-Living"]}], 
                            "Micro-Environment": [1],
                            "Molding": [1, {"bonus": [], 
                                                "option": ["Elemental Conversion*", "Molecular Conversion*", 
                                                           "Collection", "Crystallization"]}], 
                            "Weather Control": [1, {"bonus": [], 
                                                "option": ["Environmental Awareness", "True Flight", 
                                                           "Whirlwind", "Gliding"]}], 
                            "Zombie Animation*": [2, {"bonus": [], 
                                                "option": ["Extradimensional Detection", 
                                                           "Forced Reincarnation", "Summoning", 
                                                           "Undead Control", "Communication with Non-Living"]}]}

matter_conversion_powers_list = {"Coloration": [1, {"bonus": [], "option": ["Light Control"]}], 
                            "Combustion": [1, {"bonus": [], "option": ["Fire Control", "Fire Generation"]}], 
                            "Disintegration": [1],
                            "Elemental Conversion*": [2, {"bonus": [], "option": ["Matter Animation*", "Molding"]}], 
                            "Ionization": [1], "Molecular Conversion*": [2, {"bonus": [], 
                                                                             "option": ["Matter Animation*", "Molding"]}]}

matter_creation_powers_list = {"Artifact Creation*": [2, {"bonus": [], "option": ["Matter Animation*", "Hyper-Intelligence"]}], 
                            "Elemental Creation": [1, {"bonus": [], "option": ["Matter Animation*", "Machine Animation*"]}],
                            "Lifeform Creation*": [2, {"bonus": [], "option": ["Telepathy", "Mental Domination", 
                                                                               "Communicate with Animals", "Plant Control"]}], 
                            "Mechanical Creation*": [2, {"bonus": [], "option": ["Machine Animation*", "Hyper-Intelligence", 
                                                                               "Hyper-Invention"]}], 
                            "Missile Creation": [1], "Molecular Creation": [1, {"bonus": [], "option": ["Machine Animation*", "Hyper-Intelligence", 
                                                                               "Matter Animation*"]}], 
                            "Spray": [1], "Webcasting": [1]}

mental_enhancement_powers_list = {"Clairaudiance": [1, {"bonus": [], "option": ["Hyper-Hearing", "Clairvoyance", 
                                                                               "Remote Sensing"]}], 
                            "Clairvoyance": [1, {"bonus": [], "option": ["Clairaudiance", "Remote Sensing"]}], 
                            "Communicate with Animals": [1, {"bonus": [], "option": ["Linguistics", 
                                                                                     "Communicate with Cybernetics", 
                                                                                     "Communicate with Non-Living", 
                                                                                     "Communicate with Plants"]}],
                            "Communicate with Cybernetics": [1, {"bonus": [], "option": ["Linguistics"]}], 
                            "Communicate with Non-Living": [1, {"bonus": [], "option": ["Communicate with Cybernetics"]}],
                            "Communicate with Plants": [1, {"bonus": [], "option": ["Communicate with Animals", 
                                                                                     "Communicate with Non-Living", 
                                                                                     "Plant Control", "Plant Growth"]}], 
                            "Cosmic Awareness*": [2, {"bonus": [], "option": ["Hyper-Intelligence"]}],
                            "Danger Sense": [1], "Dreamtravel": [1, {"bonus": [], "option": ["Telepathy"]}], 
                            "Empathy": [1, {"bonus": [], "option": ["Clairvoyance", "Emotion Control"]}], 
                            "Free Spirit*": [2],
                            "Hallucinations*": [2], "Hyper-Intelligence": [1, {"bonus": [], 
                                                                               "option": ["Hyper-Invention", "Total Memory"]}], 
                            "Hyper-Invention": [1, {"bonus": [], "option": ["Weapons Tinkering", "Machine Animation*", "Molding", 
                                                                            "Artifact Creation*", "Mechanical Creation*"]}],
                            "Incarnation Awareness": [1, {"bonus": [], "option": ["Time Travel*", "Free Spirit*"]}], 
                            "Iron Will": [1], "Linguistics": [1, {"bonus": [], "option": ["Hyper-Intelligence"]}],
                            "Mental Duplication": [1, {"bonus": [], "option": ["Mind Drain", "Power Duplication"]}], 
                            "Mental Invisibility": [1], "Mental Probe": [1, {"bonus": [], "option": ["Telepathy", "Sensory Link"]}],
                            "Mind Blast": [1, {"bonus": [], "option": ["Telepathy", "Mental Probe"]}], 
                            "Mind Drain": [1, {"bonus": [], "option": ["Telepathy", "Mental Probe", "Mental Duplicatoin", "Mind Blast"]}], 
                            "Postcognition": [1, {"bonus": [], "option": ["Telepathy", "Time Travel*"]}],
                            "Precognition*": [2, {"bonus": [], "option": ["Telepathy", "Time Travel*"]}], 
                            "Psionic Vampirism*": [2], "Remote Sensing": [1, {"bonus": [], 
                                                                              "option": ["Clairaudiance", "Clairvoyance", 
                                                                                         "Remote Sensing"]}],
                            "Sensory Link": [1, {"bonus": [], "option": ["Telepathy"]}], 
                            "Serial Immortality*": [2], 
                            "Speechthrowing": [1, {"bonus": ["Clairaudience"], 
                                                "option": ["Clairvoyance", "Vocal Control", 
                                                           "Hyper-Hearing", "Sensory Link"]}],
                            "Telekinesis": [1, {"bonus": [], 
                                                "option": ["Matter Animation*", "Molding", "Clairvoyance", 
                                                           "Remote Sensing", "Levitation", "True Flight"]}], 
                            "Telelocation": [1, {"bonus": [], "option": ["Clairvoyance", "Extradimensional Detection"]}], 
                            "Telepathy": [1, {"bonus": [], 
                                                "option": ["Empathy", "Hallucinations*", "Mental Invisibility", 
                                                           "Mental Probe", "Mind Blast", "Mind Drain", 
                                                           "Sensory Link", "Psionic Detection"]}], 
                            "Total Memory": [1, {"bonus": [], 
                                                "option": ["Hyper-Invention", "Hyper-Intelligence", "Weapons Tinkering"]}], 
                            "Omni-Knowledge": [1]}

physical_enhancement_powers_list = {"Armor Skin": [1, {"bonus": [], "option": ["Regeneration*"]}], 
                                    "Body Resistance": [1, {"bonus": [], "option": ["Regeneration*"]}], 
                                    "Chemical Touch": [1],
                            "Digestive Adaptation": [1, {"bonus": [], "option": ["Lung Adaptability", "Body Adaptation*"]}], 
                            "Hyper-Speed": [1], "Hypnotic Voice": [1],
                            "Lung Adaptability": [1], "Pheromones*": [2], "Regeneration*": [2],
                            "Self-Revival*": [2], "Self-Sustenance": [1], "Stealth": [1],
                            "Suspended Animation": [1],"True Invulnerability*": [2], 
                            "Vocal Control": [1], "Waterbreathing": [1], 
                            "Water Freedom": [1, {"bonus":[], "option": ["Waterbreathing"]}], "Hyper-Intake/Expulsion": [1], 
                            "Hyper-Endurance": [1], "Hyper-Strength": [1]}

power_control_powers_list = {"Power Control*": [2], "Power Creation": [1], "Power Domination*": [2, {"bonus": [], 
                                                                                   "option": ["Mind Control*", "Magic Domination"]}], 
                            "Power Duplication": [1],
                            "Energy Source": [1], "Energy Source Creation*": [2], "Power Focus": [1],
                            "Power Gestalt": [1], "Nemesis": [1], "Power Transferral*": [2, {"bonus": [], 
                                                                                   "option": ["Mind Transferral*", "Magic Transferral"]}],
                            "Power Vampirism*": [2], "Residual Absorption": [1], "Power Selection": [1],
                            "Weakness Creation*": [2]}

self_alteration_powers_list = {"Age-Shift": [1], "Alter Ego": [1], "Anatomical Separation": [1],
                            "Animal Transformation": [1], "Animal Mimicry": [1], "Blending": [1],
                            "Body Adaptation*": [2], "Body Transformation*": [2], "Body Coating": [1],
                            "Bouncing Ball": [1], "Chemical Mimicry": [1], "Elongation": [1, {"bonus":[], "option": ["Plasticity"]}],
                            "Energy Body*": [2], "Energy Sheath": [1], "Evolution": [1],
                            "Growth": [1], "Imitation-Face Changer": [1], "Imitation-Human Changeling": [1],
                            "Invisibility": [1], "Mass Decrease": [1, {"bonus":[], "option": ["Gravity Manipulation"]}], 
                            "Mass Increase": [1],
                            "Phasing": [1], "Physical Gestalt": [1], "Plant Mimicry": [1],
                            "Plasticity": [1, {"bonus":["Elongation"], "option": ["Bouncing Ball"]}],
                            "Prehensile Hair": [1], "Self-Duplication*": [2],
                            "Self-Vegetation": [1], "Shapeshifting": [1], 
                            "Shrinking": [1, {"bonus":[], "option": ["Diminution"]}],
                            "Spirit Gestalt": [1], "Two-dimensionality": [1]}

travel_powers_list = {"Astral Body": [1, {"bonus":[], "option": ["Extradimensional Detection", "Magical Power"]}], 
                      "Carrier Wave": [1, {"bonus":[], "option": ["Energy Detection", "Energy Control"]}], 
                      "Dimension Travel": [1],
                      "Energy Path": [1, {"bonus":[], "option": ["Energy Detection", "Energy Control", "Energy Emission"]}], 
                      "Floating Disk": [1, {"bonus":[], "option": ["Kinetic Bolt"]}], 
                      "Gateway*": [2], "Gliding": [1, {"bonus":[], "option": ["Weather Control"]}],
                      "Hyper-Digging": [1, {"bonus":["Natural Weaponry", "Body Resistance"], 
                                            "option": ["Hyper-Strength", "Hyper-Endurance", "Armor Skin"]}], 
                      "Hyper-Leaping": [1], "Hyper-Running": [1, {"bonus":[], "option": ["Hyper-Endurance"]}],
                      "Hyper-Swimming": [1, {"bonus":["Waterbreathing", "Water Freedom"], 
                                            "option": ["Waterbreathing", "Water Freedom", "Hyper-Endurance"]}], 
                      "Levitation": [1, {"bonus":[], "option": ["Telekinesis"]}], 
                      "Rocket": [1], "Skywalk": [1, {"bonus":[], "option": ["Telekinesis"]}],
                      "Spiderclimb": [1], "Teleport Self*": [2, {"bonus":[], "option": ["Teleport Others*", "Clairvoyance"]}], 
                      "Teleport Others*": [2, {"bonus":[], "option": ["Teleport Self*", "Clairvoyance"]}],
                      "Telereformation": [1, {"bonus":[], "option": ["Free Spirit*", "Clairvoyance", "Serial Immortality*", "Lifeform Creation*"]}], 
                      "Time Travel*": [2, {"bonus":[], "option": ["Dimension Travel", "Precognition*", "Poscognition", "Reality Alteration*"]}], 
                      "Troubleseeker": [1], "True Flight": [1, {"bonus":[], 
                                                                "option": ["Body Resistance", "Armor Skin", 
                                                                           "Self-Sustenance", "Telekinesis"]}], 
                      "Water Walking": [1], "Whirlwind": [1, {"bonus":[], "option": ["Weather Control", "Matter Animation*"]}], 
                      "Spinner": [1]}

all_power_lists = {"Defensive": defensive_powers_list, 
        "Detection": detection_powers_list, 
        "Energy Control": energy_control_powers_list, 
        "Energy Emission": energy_emission_powers_list, 
        "Fighting": fighting_powers_list,
        "Illusory": illusory_powers_list, 
        "Lifeform Control": lifeform_control_powers_list,
        "Magical": magic_powers_list,
        "Matter Control": matter_control_powers_list,
        "Matter Conversion": matter_conversion_powers_list,
        "Matter Creation": matter_creation_powers_list,
        "Mental Enhancement": mental_enhancement_powers_list,
        "Physical Enhancement": physical_enhancement_powers_list,
        "Power Control": power_control_powers_list,
        "Self-Alteration": self_alteration_powers_list,
        "Travel": travel_powers_list}



professional_contacts = ["Medicine", "Law", "Law-Enforcement", "Military", 
                         "Business World", "Journalism", "Crime", "Engineering", 
                         "Psychiatry", "Detective/Espionage", "Hero Group", 
                         "Artist/Performer"]

scientific_contacts = ["Chemistry", "Biology", "Geology", "Genetics", 
                       "Archeology", "Physics", "Computers", "Electronics"]

political_contacts = ["Local", "State", "National", "Other National", 
                      "International", "Planetary"]

mystic_contact = ["Religion", "Occult Lore", "Mythology"]